[package]
name = "n-body-scrapbox"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.release]
debug = true
lto = true
panic = 'abort'
codegen-units = 1

[profile.test]
opt-level = 3

[dependencies]
plotters = "0.3.5"