[package]
name = "n-body-scrapbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
cgmath = "0.18.0"
plotters = "0.3.5"