name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build simple01
      run: |
        cd ./Plummer_model_simple
        cargo build --verbose
    - name: Run tests simple01
      run: |
        cd ./Plummer_model_simple
        cargo test --verbose
