name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build simple01
      run: |
        cd ./simple01
        cargo build --verbose
    - name: Run tests simple01
      working-directory: simple01
      run: cargo test --verbose

    - name: Build simple 02
      working-directory: simple02
      run: cargo build --verbose
    - name: Run tests simple 02
      working-directory: simple02
      run: cargo test --verbose